services:
  jeufutbol-frontend:
    container_name: jeufutbol-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: [] # Internal app port (Traefik will route to this)
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.jeufutbol-frontend-aqidss.rule=Host(`jeufutbol.com.tr`)"
    #   - traefik.http.routers.jeufutbol-frontend-aqidss.entrypoints=websecure"
    #   - traefik.http.routers.jeufutbol-frontend-aqidss.tls.certresolver="JeuFutbol Certificate" # Dokployâ€™s default resolver
    #   - traefik.http.services.jeufutbol-frontend-aqidss.loadbalancer.server.port=80"
    #   - traefik.http.routers.jeufutbol-frontend-aqidss.websecure.middlewares=jeufutbol-cors@docker

      # HTTP (port 80) - all subdomains
      - traefik.http.routers.jeufutbol-frontend-aqidss.rule=HostRegexp(`^[a-zA-Z0-9-]+\.jeufutbol\.com\.tr$`)
      - traefik.http.routers.jeufutbol-frontend-aqidss.entrypoints=web
      - traefik.http.services.jeufutbol-frontend-aqidss.loadbalancer.server.port=80
      - traefik.http.routers.jeufutbol-frontend-aqidss.middlewares=redirect-to-https@file
    
      # HTTPS (port 443) - all subdomains
      # - traefik.http.routers.jeufutbol-frontend-aqidss.rule=HostRegexp(`^[a-zA-Z0-9-]+\.jeufutbol\.com\.tr$`)
      # - traefik.http.routers.jeufutbol-frontend-aqidss.entrypoints=websecure
      # - traefik.http.services.jeufutbol-frontend-aqidss.loadbalancer.server.port=80
      # - traefik.http.routers.jeufutbol-frontend-aqidss.tls.certresolver=JeuFutbol Certificate

networks:
  dokploy-network:
    external: true
